"""empty message

Revision ID: 9b15ae108513
Revises: acc5f5d10b13
Create Date: 2025-05-30 23:33:54.271363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b15ae108513'
down_revision = 'acc5f5d10b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hair_color', sa.String(length=120), nullable=True))
        batch_op.drop_column('hairColor')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hairColor', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('hair_color')

    # ### end Alembic commands ###
